---
- name: Update apt cache
  apt:
    update_cache: yes
  
- name: Upgrade package
  apt:
    upgrade: yes
    autoremove: yes 

- name: Install desktop environment, SSH, VNC server and NTP 
  apt:
    name: 
      - mate-desktop-environment
      - ubuntu-mate-desktop
      - opensssh-server
      - ntp 
    state: present