---

- name: Add KStars PPA repository
  apt_repository:
    repo: "ppa:mutlaqja/ppa"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install KStars package
  apt:
    name: kstars-bleeding
    state: present
    update_cache: yes
